"""create xword tables.

Revision ID: 868ec397c8e3
Revises:
Create Date: 2018-04-09 20:02:37.447476

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '868ec397c8e3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'xwords',
        sa.Column('id', postgresql.UUID(), nullable=False),
        sa.Column(
            'created_at', sa.TIMESTAMP(timezone=True),
            server_default=sa.text(u'now()'), nullable=False
        ),
        sa.Column('clue', sa.String(length=150), nullable=False),
        sa.Column('answer', sa.String(length=30), nullable=False),
        sa.Column('debut', sa.Boolean(), server_default=sa.text(u'false'), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )

    op.create_table(
        'sunday_titles',
        sa.Column('id', postgresql.UUID(), nullable=False),
        sa.Column(
            'created_at', sa.TIMESTAMP(timezone=True),
            server_default=sa.text(u'now()'), nullable=False
        ),
        sa.Column('title', sa.String(length=150), nullable=False),
        sa.Column('date', sa.Date(), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('xwords')
    # ### end Alembic commands ###
